import{useEffect,useMemo,useState}from'react';import{Navigate,Route,Routes,useNavigate}from'react-router-dom';import{supabase}from'./lib/supabase';
const OWNER=['Overview','Churches','Add Church','Subscriptions','Platform Users','Activity','System Health','Settings'];
const CHURCH=['Dashboard','People','First Timers','Follow-Up','Attendance','Giving','Finance','Events','Ministries','Groups','Volunteers','Communication','Media','Testimonies','Prayer','Missions','Forms','Reports','Settings'];
const labels:any={first_timer_cases:'First Timers',follow_up_interactions:'Follow-Up',giving_records:'Giving',attendance_records:'Attendance',communication_campaigns:'Communication',media_items:'Media',prayer_requests:'Prayer',mission_reports:'Missions',form_definitions:'Forms',volunteer_assignments:'Volunteers'};
const cfg:any={
 People:{table:'people',fields:[['first_name','First name'],['last_name','Last name'],['phone','Phone'],['email','Email'],['gender','Gender'],['stage','Stage']],select:'id,first_name,last_name,phone,email,gender,stage,created_at'},
 'First Timers':{table:'first_timer_cases',fields:[],select:'id,status,first_visit_at,next_action_at,person_id,created_at'},
 'Follow-Up':{table:'follow_up_interactions',fields:[['interaction_type','Type'],['outcome','Outcome'],['notes','Notes'],['next_action_at','Next action']],select:'id,interaction_type,outcome,notes,next_action_at,created_at'},
 Giving:{table:'giving_records',fields:[['amount','Amount'],['giving_type','Type'],['payment_method','Payment method'],['reference','Reference']],select:'id,amount,currency,giving_type,payment_method,reference,given_at'},
 Events:{table:'events',fields:[['title','Title'],['description','Description'],['starts_at','Starts at'],['location','Location'],['event_type','Type']],select:'id,title,starts_at,location,event_type,is_public'},
 Ministries:{table:'ministries',fields:[['name','Name'],['description','Description']],select:'id,name,description,is_active,created_at'},
 Groups:{table:'groups',fields:[['name','Name'],['group_type','Type'],['meeting_details','Meeting details']],select:'id,name,group_type,meeting_details,is_active'},
 Communication:{table:'communication_campaigns',fields:[['channel','Channel'],['audience_type','Audience'],['subject','Subject'],['message','Message']],select:'id,channel,audience_type,subject,message,status,created_at'},
 Media:{table:'media_items',fields:[['title','Title'],['media_type','Type'],['speaker','Speaker'],['media_url','Media URL']],select:'id,title,media_type,speaker,media_url,published_at,is_public'},
 Testimonies:{table:'testimonies',fields:[['title','Title'],['testimony','Testimony'],['video_url','Video URL']],select:'id,title,testimony,status,is_featured,submitted_at'},
 Prayer:{table:'prayer_requests',fields:[['title','Title'],['request','Prayer request'],['confidentiality','Confidentiality']],select:'id,title,request,confidentiality,status,created_at'},
 Missions:{table:'mission_reports',fields:[['title','Title'],['summary','Summary'],['souls_won','Souls won'],['attendees','Attendees']],select:'id,title,summary,souls_won,attendees,created_at'},
 Volunteers:{table:'volunteer_assignments',fields:[['assignment','Assignment'],['status','Status']],select:'id,assignment,status,created_at'},
 Forms:{table:'form_definitions',fields:[['name','Name'],['form_type','Type']],select:'id,name,form_type,is_public,created_at'}
};
function Login(){const n=useNavigate(),[e,se]=useState(''),[p,sp]=useState(''),[m,sm]=useState('');async function go(x:any){x.preventDefault();sm('');const{data,error}=await supabase.auth.signInWithPassword({email:e,password:p});if(error)return sm(error.message);n(data.user.app_metadata?.platform_owner===true?'/owner':'/portal',{replace:true})}return <main className="center"><form className="card login" onSubmit={go}><div className="brand">CHURCH MANAGEMENT SYSTEM</div><span className="pill">SECURE ACCESS</span><h1>Welcome back</h1><p>One account. The right workspace for your ministry role.</p><label>Email<input type="email" value={e} onChange={x=>se(x.target.value)} required/></label><label>Password<input type="password" value={p} onChange={x=>sp(x.target.value)} required/></label>{m&&<div className="error">{m}</div>}<button>Sign in</button></form></main>}
function Owner(){const[ok,setOk]=useState<boolean|null>(null),[tab,setTab]=useState('Overview'),[orgs,setOrgs]=useState<any[]>([]);async function load(){const{data}=await supabase.from('organizations').select('*').order('created_at',{ascending:false});setOrgs(data||[])}useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user)return setOk(false);let own=user.app_metadata?.platform_owner===true;if(!own){const{data}=await supabase.from('profiles').select('is_platform_owner').eq('id',user.id).maybeSingle();own=!!data?.is_platform_owner}setOk(own);if(own)load()})()},[]);if(ok===null)return <Busy/>;if(!ok)return <Navigate to="/portal" replace/>;return <Shell title={tab} nav={OWNER} tab={tab} setTab={setTab} footer="PLATFORM OWNER · Ezra Ackon">{tab==='Add Church'?<Onboard done={()=>{load();setTab('Churches')}}/>:tab==='Churches'?<Churches rows={orgs}/>:tab==='Overview'?<OwnerHome rows={orgs}/>:<OwnerModule name={tab} orgs={orgs}/>}</Shell>}
function OwnerHome({rows}:any){return <><div className="stats"><Stat n={rows.length} t="Churches"/><Stat n={rows.filter((x:any)=>x.status==='active').length} t="Active"/><Stat n={rows.filter((x:any)=>x.subscription_status==='trial').length} t="On trial"/><Stat n="Online" t="Platform"/></div><Panel title="Platform command centre"><p>Manage your entire church network from one secure owner account.</p></Panel></>}
function Churches({rows}:any){return <Panel title="Church network">{rows.length?rows.map((o:any)=><div className="row" key={o.id}><div><b>{o.name}</b><small>{o.status} · {o.subscription_status} · {o.plan_code}</small></div><a className="btn" href={'/portal?org='+o.id}>Open portal</a></div>):<Empty text="No churches yet."/ >}</Panel>}
function Onboard({done}:any){const[f,sf]=useState<any>({name:'',contact_email:'',contact_phone:'',headquarters_name:'Headquarters',plan_code:'starter'}),[m,sm]=useState('');const set=(k:string,v:string)=>sf({...f,[k]:v});async function create(){sm('Creating…');const slug=f.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+crypto.randomUUID().slice(0,8);const{data:o,error}=await supabase.from('organizations').insert({name:f.name,slug,contact_email:f.contact_email||null,contact_phone:f.contact_phone||null,status:'onboarding',subscription_status:'trial',plan_code:f.plan_code}).select().single();if(error)return sm(error.message);const{error:b}=await supabase.from('branches').insert({organization_id:o.id,name:f.headquarters_name,code:'HQ',is_headquarters:true});if(b)return sm(b.message);sm('Church created.');setTimeout(done,500)}return <Panel title="Add Church"><div className="grid2"><Field l="Church name" v={f.name} set={(v:string)=>set('name',v)}/><Field l="Contact email" v={f.contact_email} set={(v:string)=>set('contact_email',v)}/><Field l="Phone" v={f.contact_phone} set={(v:string)=>set('contact_phone',v)}/><Field l="Headquarters" v={f.headquarters_name} set={(v:string)=>set('headquarters_name',v)}/></div><button disabled={!f.name} onClick={create}>Create church</button>{m&&<p className="notice">{m}</p>}</Panel>}
function OwnerModule({name,orgs}:any){if(name==='Subscriptions')return <Panel title="Subscriptions">{orgs.map((o:any)=><div className="row" key={o.id}><div><b>{o.name}</b><small>{o.plan_code}</small></div><span className="pill">{o.subscription_status}</span></div>)}</Panel>;return <Panel title={name}><p>This owner workspace is active and connected to the platform database.</p></Panel>}
function Portal(){const[org,setOrg]=useState<any>(null),[tab,setTab]=useState('Dashboard'),[load,setLoad]=useState(true),[role,setRole]=useState('platform_owner');useEffect(()=>{(async()=>{const q=new URLSearchParams(location.search).get('org');const{data:{user}}=await supabase.auth.getUser();if(!user)return setLoad(false);let own=user.app_metadata?.platform_owner===true;if(q&&own){const{data}=await supabase.from('organizations').select('*').eq('id',q).single();setOrg(data);setLoad(false);return}if(own&&!q){location.replace('/owner');return}const{data:r}=await supabase.from('organization_users').select('organization_id,role,organizations(*)').eq('user_id',user.id).eq('is_active',true).limit(1);if(r?.[0]){setOrg((r[0] as any).organizations);setRole(r[0].role)}setLoad(false)})()},[]);if(load)return <Busy/>;if(!org)return <main className="center"><div className="card"><h2>No church portal assigned</h2><a className="btn" href="/">Return to sign in</a></div></main>;return <Shell title={tab} nav={CHURCH} tab={tab} setTab={setTab} footer={org.name}>{tab==='Dashboard'?<Dashboard org={org}/>:tab==='Finance'?<Finance org={org}/>:tab==='Reports'?<Reports org={org}/>:tab==='Settings'?<Settings org={org}/>:tab==='Attendance'?<Attendance org={org}/>:cfg[tab]?<Crud org={org} name={tab} c={cfg[tab]}/>:<Panel title={tab}><p>Workspace ready.</p></Panel>}</Shell>}
function Dashboard({org}:any){const[s,ss]=useState<any>(null);useEffect(()=>{supabase.from('organization_dashboard_stats').select('*').eq('organization_id',org.id).maybeSingle().then(({data})=>ss(data))},[org.id]);return <><div className="stats"><Stat n={s?.people_count??0} t="People"/><Stat n={s?.member_count??0} t="Members"/><Stat n={s?.open_follow_up_count??0} t="Follow-Up"/><Stat n={'GHS '+Number(s?.giving_this_month||0).toFixed(2)} t="Giving this month"/></div><Panel title={org.name}><p>Complete ministry operations from first visit through membership, care, service, giving and communication.</p><div className="quick"><span>People</span><span>First Timers</span><span>Attendance</span><span>Giving</span><span>Communication</span></div></Panel></>}
function Crud({org,name,c}:any){const[rows,sr]=useState<any[]>([]),[form,sf]=useState<any>({}),[q,sq]=useState(''),[m,sm]=useState('');async function load(){const{data,error}=await supabase.from(c.table).select(c.select).eq('organization_id',org.id).order('created_at',{ascending:false}).limit(100);if(error)sm(error.message);else sr(data||[])}useEffect(()=>{load()},[org.id,name]);async function add(){let body:any={organization_id:org.id,...form};if(c.table==='people'){if(!body.first_name||!body.last_name)return sm('First and last name are required.');body.stage=body.stage||'visitor'}if(c.table==='events'&&!body.starts_at)return sm('Start date/time is required.');if(c.table==='giving_records')body.amount=Number(body.amount||0);const{error}=await supabase.from(c.table).insert(body);if(error)return sm(error.message);sf({});sm('Saved successfully.');load()}const filtered=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase()));return <><Panel title={name}><div className="toolbar"><input placeholder={'Search '+name.toLowerCase()} value={q} onChange={e=>sq(e.target.value)}/><span>{filtered.length} records</span></div>{c.fields.length>0&&<div className="entry">{c.fields.map((f:any)=><Field key={f[0]} l={f[1]} v={form[f[0]]||''} set={(v:string)=>sf({...form,[f[0]]:v})}/>)}<button onClick={add}>Save</button></div>}{m&&<p className="notice">{m}</p>}</Panel><Panel title={'Recent '+name}>{filtered.length?<Table rows={filtered}/>:<Empty text={'No '+name.toLowerCase()+' records yet.'}/>}</Panel></>}
function Attendance({org}:any){const[events,se]=useState<any[]>([]),[people,sp]=useState<any[]>([]),[event,setEvent]=useState(''),[person,setPerson]=useState(''),[m,sm]=useState('');useEffect(()=>{supabase.from('events').select('id,title,starts_at').eq('organization_id',org.id).then(({data})=>se(data||[]));supabase.from('people').select('id,first_name,last_name').eq('organization_id',org.id).then(({data})=>sp(data||[]))},[org.id]);async function check(){if(!event||!person)return sm('Choose an event and person.');const{error}=await supabase.from('attendance_records').insert({organization_id:org.id,event_id:event,person_id:person});sm(error?error.message:'Checked in successfully.')}return <Panel title="Attendance Check-In"><label>Event<select value={event} onChange={e=>setEvent(e.target.value)}><option value="">Select event</option>{events.map(x=><option value={x.id}>{x.title}</option>)}</select></label><label>Person<select value={person} onChange={e=>setPerson(e.target.value)}><option value="">Select person</option>{people.map(x=><option value={x.id}>{x.first_name} {x.last_name}</option>)}</select></label><button onClick={check}>Check in</button>{m&&<p className="notice">{m}</p>}</Panel>}
function Finance({org}:any){return <><Crud org={org} name="Giving" c={cfg.Giving}/><FinanceTable org={org} table="expenses" title="Expenses" fields={[['description','Description'],['amount','Amount'],['vendor','Vendor']]}/><FinanceTable org={org} table="pledges" title="Pledges" fields={[['amount','Amount'],['amount_paid','Amount paid'],['status','Status']]}/></>}
function FinanceTable({org,table,title,fields}:any){const[r,sr]=useState<any[]>([]),[f,sf]=useState<any>({});async function load(){const{data}=await supabase.from(table).select('*').eq('organization_id',org.id).limit(100);sr(data||[])}useEffect(()=>{load()},[org.id]);async function add(){await supabase.from(table).insert({organization_id:org.id,...f,amount:Number(f.amount||0),...(table==='pledges'?{amount_paid:Number(f.amount_paid||0)}:{})});sf({});load()}return <Panel title={title}><div className="entry">{fields.map((x:any)=><Field l={x[1]} v={f[x[0]]||''} set={(v:string)=>sf({...f,[x[0]]:v})}/>)}<button onClick={add}>Save</button></div><Table rows={r}/></Panel>}
function Reports({org}:any){const[s,ss]=useState<any>();useEffect(()=>{supabase.from('organization_dashboard_stats').select('*').eq('organization_id',org.id).maybeSingle().then(({data})=>ss(data))},[org.id]);return <Panel title="Reports & Analytics"><div className="stats"><Stat n={s?.people_count||0} t="People"/><Stat n={s?.member_count||0} t="Members"/><Stat n={s?.upcoming_events_count||0} t="Upcoming events"/><Stat n={'GHS '+Number(s?.expenses_this_month||0).toFixed(2)} t="Expenses this month"/></div></Panel>}
function Settings({org}:any){const[f,sf]=useState<any>({}),[m,sm]=useState('');useEffect(()=>{supabase.from('church_settings').select('*').eq('organization_id',org.id).maybeSingle().then(({data})=>sf(data||{}))},[org.id]);async function save(){const{error}=await supabase.from('church_settings').upsert({organization_id:org.id,...f});sm(error?error.message:'Settings saved.')}return <Panel title="Church Settings"><Field l="Welcome message" v={f.welcome_message||''} set={(v:string)=>sf({...f,welcome_message:v})}/><Field l="Livestream URL" v={f.livestream_url||''} set={(v:string)=>sf({...f,livestream_url:v})}/><Field l="Giving instructions" v={f.giving_instructions||''} set={(v:string)=>sf({...f,giving_instructions:v})}/><button onClick={save}>Save settings</button>{m&&<p className="notice">{m}</p>}</Panel>}
function Shell({title,nav,tab,setTab,footer,children}:any){return <div className="shell"><aside><div className="brand">CHURCH MANAGEMENT SYSTEM</div><nav>{nav.map((x:string)=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav><footer>{footer}<button className="logout" onClick={async()=>{await supabase.auth.signOut();location.href='/'}}>Sign out</button></footer></aside><main><header><div><small>SECURE WORKSPACE</small><h1>{title}</h1></div><span className="status">● Live</span></header>{children}</main></div>}
function Panel({title,children}:any){return <section className="panel"><h2>{title}</h2>{children}</section>}function Stat({n,t}:any){return <div className="panel stat"><h2>{n}</h2><small>{t}</small></div>}function Empty({text}:any){return <div className="empty">{text}</div>}function Busy(){return <div className="center">Securing workspace…</div>}
function Field({l,v,set}:any){return <label>{l}<input value={v} onChange={e=>set(e.target.value)}/></label>}
function Table({rows}:any){if(!rows?.length)return <Empty text="No records yet."/>;const keys=Object.keys(rows[0]).filter(k=>k!=='id'&&!k.endsWith('_id')).slice(0,6);return <div className="tablewrap"><table><thead><tr>{keys.map(k=><th>{k.replace(/_/g,' ')}</th>)}</tr></thead><tbody>{rows.map((r:any)=><tr key={r.id||JSON.stringify(r)}>{keys.map(k=><td>{r[k]===null?'—':typeof r[k]==='boolean'?(r[k]?'Yes':'No'):String(r[k]).slice(0,80)}</td>)}</tr>)}</tbody></table></div>}
export default function App(){return <Routes><Route path="/" element={<Login/>}/><Route path="/owner/*" element={<Owner/>}/><Route path="/portal/*" element={<Portal/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes>}